name: Build Boxes
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
  schedule:
    - cron: "0 11 * * 0"
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build-linux-box:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get CalVer
        id: get_calver
        run: |
          CalVer=$(date '+%Y.%m.%d')
          echo "::set-output name=CalVer::$CalVer"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: false
          tags: |
            ajkayalan/docker-linux-dev-box:latest

      - name: Test
        run: docker run -v $PWD/tests:/tests ajkayalan/docker-linux-dev-box ./tests/run_integration_tests.sh

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ajkayalan/docker-linux-dev-box:latest
            ajkayalan/docker-linux-dev-box:${{ steps.get_calver.outputs.CalVer }}
            ghcr.io/ajkayalan/docker-linux-dev-box:latest
            ghcr.io/ajkayalan/docker-linux-dev-box:${{ steps.get_calver.outputs.CalVer }}
