name: Build Boxes
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
  schedule:
    - cron:  '0 11 * * 0'
defaults:
  run:
    shell: bash
jobs:
  build-linux-box:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get CalVer
        run: |
          CalVer=$(date '+%Y.%m.%d')
          echo "::set-env name=CalVer::$CalVer"
      - name: Build And Push To Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajkayalan/docker-linux-dev-box
          tag_with_ref: true
          tag_with_sha: true
          tags: |
            ajkayalan/docker-linux-dev-box:$CalVer